### ISSUE TITLE
User access removed, access is now via a team

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/django-moj-irat#11]
Hi there 

 This user had Direct Member access to this repository and access via a team. 

 Access is now only via a team. 

 If you have any questions, please post in #ask-operations-engineering on Slack. 

 This issue can be closed.

**Comment by ushkarev** [comment]
@AntonyBishop I don't understand, who is "this user"? There are no collaborators in the settings for this project that aren't groups.
